-- SQLite schema for Student Performance Evaluation System

-- Table to store student academic records per subject
CREATE TABLE IF NOT EXISTS student_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL,
    student_name TEXT NOT NULL,
    register_number TEXT NOT NULL,
    roll_number TEXT NOT NULL,
    subject TEXT NOT NULL,
    study_hours REAL,
    attendance REAL,
    subject_score REAL,
    internal_mark REAL,
    UNIQUE(student_id, subject)  -- prevent duplicate subject entries for the same student
);

-- Table to store evaluations generated by teachers/LLM
CREATE TABLE IF NOT EXISTS evaluations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    record_id INTEGER NOT NULL,
    pass_fail_result TEXT,
    confidence_level REAL,
    teacher_comment TEXT,
    ai_recommendation TEXT,
    evaluation_status TEXT CHECK(evaluation_status IN ('PENDING','COMPLETED')) DEFAULT 'PENDING',
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(record_id) REFERENCES student_records(id)
);

-- Basic auth tables for teachers and students (simplified)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT CHECK(role IN ('TEACHER','STUDENT')) NOT NULL,
    linked_student_id TEXT  -- for role=STUDENT
);
